login:
    path: /login
    defaults: { _controller: ezpublish.security.controller:loginAction }

login_check:
    path: /login_check

logout:
    path: /logout

app.search:
    path: /content/search
    defaults:
        _controller: app.controller.search:showSearchResultsAction
    methods: [GET]

app.subscribe:
    path: /Subscribe
    defaults:
        _controller: app.controller.subscribe:confirm
    methods: [POST]

app.user_preferences:
    path: /user/preferences
    defaults:
        _controller: app.controller.user_profile_controller:showPreferencesAction
    methods: [GET, POST]

netgen_tags_admin_autocomplete:
    path: /tags/admin/field/autocomplete
    defaults:
        _controller: eztags.admin.controller.field:autoCompleteAction
        _method: GET
    options:
        expose: true

kernel.internal:
    resource: '@EzPublishCoreBundle/Resources/config/routing/internal.yml'

kernel.rest:
    resource: '@EzPublishRestBundle/Resources/config/routing.yml'
    prefix: '%ezpublish_rest.path_prefix%'

kernel.rest.options:
    resource: '@EzPublishRestBundle/Resources/config/routing.yml'
    prefix: '%ezpublish_rest.path_prefix%'
    type: rest_options

ezplatform.admin_ui:
    resource: '@EzPlatformAdminUiBundle/Resources/config/routing.yml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'

_ezplatformRepositoryFormsRoutes:
    resource: '@EzSystemsRepositoryFormsBundle/Resources/config/routing.yml'

ezplatform.ee.dependencies.bazinga:
    resource: '@BazingaJsTranslationBundle/Resources/config/routing/routing.yml'

ezplatform.ee.notifications:
    resource: '@NotificationBundle/Resources/config/routing.yml'

ezplatform.fieldtype.page:
    resource: '@EzPlatformPageFieldTypeBundle/Resources/config/routing.yml'

ezplatform.page_builder:
    resource: '@EzPlatformPageBuilderBundle/Resources/config/routing.yml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'

fos.js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'

_eztagsRoutes:
    resource: "@NetgenTagsBundle/Resources/config/routing.yml"

_novaezseoRoutes:
    resource: "@NovaeZSEOBundle/Controller/"
    type:     annotation
    prefix:   /

# Custom redirection from /ez to /admin, feel free to adjust to your needs or remove if you don't need it
platform1_admin_route:
    path: /ez
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /admin
        permanent: true
