# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    app.controller.menu:
        class: AppBundle\Controller\MenuController
        public: true
        arguments:
            - '@templating'
            - '@ezpublish.api.service.search'
            - '@app.query_type.menu'
            - '%app.top_menu.parent_location_id%'
            - '%app.top_menu.includedContentTypeIdentifier%'

    app.query_type.menu:
        class: AppBundle\QueryType\MenuQueryType
        calls:
            - [setLanguages, [$languages$]]
        tags:
            - { name: ezpublish.query_type }

    app.controller.contactform:
        class: AppBundle\Controller\ContactFormController
        public: true
        arguments:
            - '@form.factory'
            - '@app.mail.sender'
            - '@templating'
            - '@hautelook.router.template'

    app.controller.product_list_controller:
        class: AppBundle\Controller\ProductListController
        public: true
        arguments:
            - '@ezpublish.query_type_content_view_mapper'
            - '@ezpublish.api.service.search'
            - '@form.factory'

    app.mail.sender:
        class: AppBundle\Mail\Sender
        public: true
        arguments:
            - '@mailer'
            - '@translator'
            - '@templating'
            - '%app.contact_form.sender_email%'
            - '%app.contact_form.recipient_email%'

    app.twig.content_info_by_location_id_extension:
        class: AppBundle\Twig\ContentInfoByLocationIdExtension
        arguments:
            - '@ezpublish.api.service.location'
            - '@ezpublish.api.service.content'

    AppBundle\Twig\YoutubeIdExtractorExtension:
        tags:
            - { name: twig.extension }

    AppBundle\Event\PlacesBlockListener: ~

    AppBundle\Event\TastesBlockListener: ~

    app.controller.recommendations:
        class: AppBundle\Controller\RecommendationsController
        public: true
        arguments:
            - '@ezpublish.api.service.location'
            - '@ezpublish.api.service.search'
            - '@ezpublish.api.service.content'
            - '@router'
            - '@templating'

    AppBundle\Twig\RecommendationsExtension:
        arguments:
            - '@ezpublish.config.resolver'
        tags:
            - { name: twig.extension }

    AppBundle\Twig\SearchResultExtractorExtension:
        tags:
            - { name: twig.extension }

    AppBundle\PremiumContent\HtmlRenderer: ~
    AppBundle\User\UserGroups: ~

    AppBundle\Twig\PremiumContentExtension:
        arguments:
            - '@AppBundle\PremiumContent\HtmlRenderer'
            - '@AppBundle\User\UserGroups'
            - '%app.premium_content.allowed_user_groups.location_ids%'
        tags:
            - { name: twig.extension }

    AppBundle\Twig\ContentDescriptionExtension:
        arguments:
        - "@ezpublish.field_helper"
        - "@?logger"
        tags:
            - { name: twig.extension }

    AppBundle\Event\TemplateAttributeBlockNameListener:
        tags:
            - { name: kernel.event_subscriber }

    AppBundle\Event\PageFieldType\Attribute\AttributeSerializationSubscriber: ~

    AppBundle\Menu\ReorderMenuListener:
        tags:
            - { name: kernel.event_listener, event: ezplatform_admin_ui.menu_configure.main_menu, method: moveTagsToLast, priority: -45 }
